### ISSUE TITLE
Match collapsed theming with navigation controls

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-geocoder#296]
In this collapsed state, the container has a wide box shadow, slightly grey icon and different dimensions:

<img width="102" alt="Screen Shot 2019-09-20 at 9 46 07 AM" src="https://user-images.githubusercontent.com/61150/65331989-d8751680-db8b-11e9-898b-27835be494c9.png">

For consistency with the default navigation controls, I think the styling to conform so its flush and resembles a member of the same system.

cc/ @scottsfarley93

**Comment by kmanzana** [comment]
Did you end up styling this to match? or has someone else and can they share the code?

**Comment by kmanzana** [comment]
for future reference or in case it helps anyone, here is how i styled the button 

```css
.mapboxgl-ctrl-geocoder {
  height: 29px;
  box-shadow: 0 0 0 2px rgba(0, 0, 0, 0.1);
}
.mapboxgl-ctrl-geocoder .mapboxgl-ctrl-geocoder--icon-search {
  top: 0;
  left: 5px;
  height: 100%;
  fill: rgba(0, 0, 0, 0.87);
}
.mapboxgl-ctrl-geocoder .mapboxgl-ctrl-geocoder--input {
  height: 29px;
}
.mapboxgl-ctrl-geocoder.mapboxgl-ctrl-geocoder--collapsed {
  width: 29px !important;
  min-width: 29px;
}
.mapboxgl-ctrl-geocoder .mapboxgl-ctrl-geocoder--pin-right > * {
  top: 4px;
}
```
button collapsed
![image](https://user-images.githubusercontent.com/2164013/106514923-8429b880-649a-11eb-9d14-0fcf22296753.png)

search box expanded
![image](https://user-images.githubusercontent.com/2164013/106514856-6ceacb00-649a-11eb-9399-500ca3c88d3a.png)

if the maintainers fix this or someone wants to open a PR, may be easiest to add a `.mapbox-ctrl-group` to the top level `div`, then put the `svg` inside of a `button`. this would allow styles applied by `` from Mapbox GL to get applied here too, may help, but haven't dug into that myself.
